AMC/ViewModels/User/UserViewModel.cs
using AMC.CORE.Enumerations;

namespace AMC.WEB.ViewModels.User
{
    public class UserViewModel
    {
        public string Username { get; set; }
        public UserRole Role { get; set; }

        public string RoleName
        {
            get
            {
                return Role.ToFriendlyString();
            }
        }

        public UserViewModel()
        {
        }

        public UserViewModel(CORE.Models.User user)
        {
            Username = user.Username;
            Role = user.Role;
        }
    }
}

AMC/ViewModels/Users/DeleteViewModel.cs
namespace AMC.WEB.ViewModels.Users
{
    public class DeleteViewModel
    {
        public string Username { get; set; }
    }
}

AMC/ViewModels/Users/SetupViewModel.cs
using AMC.CORE.Enumerations;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AMC.WEB.ViewModels.Users
{
    public class SetupViewModel
    {
        public string Username { get; set; }
        
        [Required]
        public UserRole Role { get; set; }
        public List<SelectListItem> RoleList { get; set; }

        public SetupViewModel()
        {
        }
    } 
}

AMC/ViewModels/Users/UsersListViewModel.cs
using System.Collections.Generic;

namespace AMC.WEB.ViewModels.Users
{
    public class UsersListViewModel
    {
        public IEnumerable<UsersViewModel> Users { get; set; }
    }
}

AMC/ViewModels/Users/UsersViewModel.cs
using AMC.CORE.Enumerations;

namespace AMC.WEB.ViewModels.Users
{
    public class UsersViewModel
    {
        public string Username { get; set; }
        public UserRole Role { get; set; }
        public bool IsRegistered { get; set; }
        public bool IsSetup { get; set; }

        public string RoleName
        {
            get
            {
                return Role.ToFriendlyString();
            }
        }

        public UsersViewModel()
        {
        }

        public UsersViewModel(CORE.Models.User user)
        {
            Username = user.Username;
            Role = user.Role;
            IsRegistered = user.IsRegistered;
            IsSetup = user.IsSetup;
        }
    }
}

AMC/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using AMC.BLL.Interfaces;
using AMC.WEB.ViewModels.Users;
using System.Linq;
using AMC.CORE.Models;
using AMC.WEB.ViewModels;
using AMC.CORE.Enumerations;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace AMC.WEB.Controllers
{
    [Authorize(Policy = "Admin")]
    public class UsersController : Controller
    {
        IUserManager _userManager;

        public UsersController(IUserManager userManager)
        {
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetTable(DataTableRequest request)
        {
            AjaxResponse response = new AjaxResponse();
            DataTableResult<User> table = _userManager.GetUsersTable(request);

            response.Data = new DataTableResult<UsersViewModel>(table.Items.Select(user => new UsersViewModel(user)), table.Length);
            return Json(response);
        }

        [HttpGet]
        [Route("/Users/Setup/{username}")]
        public IActionResult Setup(string username)
        {
            // Check if the username exists
            User user = _userManager.Read(username);
            if (user == null)
            {
                // TODO: add tempdata msg
                return RedirectToAction("Index");
            }

            SetupViewModel model = new SetupViewModel();
            model.Username = user.Username;
            model.Role = user.Role;

            // Create the UserRole list
            model.RoleList = new List<SelectListItem>();
            foreach (UserRole role in Enum.GetValues(typeof(UserRole)))
            {
                model.RoleList.Add(new SelectListItem() { Text = role.ToFriendlyString(), Value = role.ToString() });
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Setup(SetupViewModel model)
        {
            // Check if the username exists
            User user = _userManager.Read(model.Username);
            if (user == null)
            {
                // TODO: add tempdata msg
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                // Setup the user
                user.Role = model.Role;

                if(_userManager.Setup(user) > 0)
                {
                    return RedirectToAction("Index");
                }

                ModelState.AddModelError("Username", "User could not be setup");
            }
            
            // Create the UserRole list
            model.RoleList = new List<SelectListItem>();
            foreach (UserRole role in Enum.GetValues(typeof(UserRole)))
            {
                model.RoleList.Add(new SelectListItem() { Text = role.ToFriendlyString(), Value = role.ToString() });
            }

            return View(model);
        }

        [HttpGet]
        [Route("/Users/Delete/{username}")]
        public IActionResult Delete(string username)
        {
            // Check if the username exists
            User user = _userManager.Read(username);
            if (user == null)
            {
                // TODO: add tempdata msg
                return RedirectToAction("Index");
            }

            DeleteViewModel model = new DeleteViewModel();
            model.Username = user.Username;

            return PartialView("_Delete", model);
        }

        [HttpPost]
        public IActionResult Delete(DeleteViewModel model)
        {
            // Check if the username exists
            User user = _userManager.Read(model.Username);
            if (user == null)
            {
                // TODO: add tempdata msg
                return RedirectToAction("Index");
            }
            
            if(ModelState.IsValid)
            {
                if (_userManager.Delete(user.Id) > 0)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(model);
        }

        //[HttpGet]
        //public IActionResult Edit(string username)
        //{
        //    // Check if the username exists
        //    User user = _userManager.Read(username);
        //    if (user == null)
        //    {
        //        // TODO: add tempdata msg
        //        return RedirectToAction("Index");
        //    }

        //    EditViewModel model = new EditViewModel();
        //    model.Username = user.Username;
        //    model.Role = user.Role;
        //    model.IsRegistered = user.IsRegistered;
        //    model.IsSetup = user.IsSetup;

        //    // Create the UserRole list
        //    model.RoleList = new List<SelectListItem>();
        //    foreach (UserRole role in Enum.GetValues(typeof(UserRole)))
        //    {
        //        model.RoleList.Add(new SelectListItem() { Text = role.ToFriendlyString(), Value = role.ToString() });
        //    }

        //    return View(model);
        //}

        //[HttpPost]
        //public IActionResult Edit(EditViewModel model)
        //{
        //    // Check if the username exists
        //    User user = _userManager.Read(model.Username);
        //    if (user == null)
        //    {
        //        // TODO: add tempdata msg
        //        return RedirectToAction("Index");
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        // Set the user's role
        //        user.Role = model.Role;
        //        user.IsRegistered = model.IsRegistered;
        //        user.IsSetup = model.IsSetup;

        //        if (_userManager.Setup(user) > 0)
        //        {
        //            return RedirectToAction("Index");
        //        }

        //        ModelState.AddModelError("Username", "User could not be setup");
        //    }

        //    // Create the UserRole list
        //    model.RoleList = new List<SelectListItem>();
        //    foreach (UserRole role in Enum.GetValues(typeof(UserRole)))
        //    {
        //        model.RoleList.Add(new SelectListItem() { Text = role.ToFriendlyString(), Value = role.ToString() });
        //    }

        //    return View(model);
        //}
    }
}

AMC/Views/Users/Index.cshtml
@section scripts{
    <script>
        $(function () {
            $('#users-table').DataTable({
                processing: true,
                serverSide: true,
                language: {
                    infoFiltered: '',
                    lengthMenu: 'Show _MENU_',
                    search: 'Search '
                },
                ajax: function (data, callback, settings) {
                    AjaxPost('/Users/GetTable', data, function (response) {
                        callback({
                            recordsTotal: response.length,
                            recordsFiltered: response.length,
                            data: response.items
                        });
                    });
                },
                columns: [
                    {
                        title: 'Name',
                        data: 'username',
                        render: function (data, type, row, meta) {
                            return row['username'];
                        }
                    },
                    {
                        title: 'Role',
                        data: 'roleName',
                        render: function (data, type, row, meta) {
                            return row['roleName'];
                        }
                    },
                    {
                        title: 'Edit',
                        render: function (data, type, row, meta) {
                            if (row['isSetup']) {
                                return '<a><span class="glyphicon glyphicon-pencil"><span></a>';                                
                            }
                            return '<a href="/Users/Setup/' + row['username'] + '"><span class="glyphicon glyphicon-wrench"><span></a>';
                        }
                    },
                    {
                        title: 'Delete',
                        render: function (data, type, row, meta) {
                            return '<a class="toggle-delete-modal" data-username="' + row['username'] + '"><span class="glyphicon glyphicon-remove"><span></a>';
                        }
                    }
                ]
            });
            
            $('table').on('click', '.toggle-delete-modal', function () {
                var username = $(this).data('username');
                $('#delete-modal-container').load('/Users/Delete/' + username, function () {
                    $('#delete-modal').modal();
                });
            });
        });
    </script>
}

<div class="container">
    <h2>User Management</h2>
    <hr />    
    <table class="table" id="users-table"></table>
</div>

<div id="delete-modal-container"></div>

AMC/Views/Users/Setup.cshtml
@model SetupViewModel

<h3>User Setup</h3>
<h5>Set a newly registered user's role and give them access to the site.</h5>
<hr />

<form method="post">
    <div class="form-group">
        <label asp-for="Username"></label>
        <input asp-for="Username" class="form-control" value="@Model.Username" readonly />
    </div>
    <div class="form-group">
        <label asp-for="Role"></label>
        <select asp-for="Role" asp-items="Model.RoleList" class="form-control"></select>
        <span asp-validation-for="Role" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

AMC/Views/Users/_Delete.cshtml
@model DeleteViewModel

<form method="post" asp-controller="Users" asp-action="Delete">
    <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="delete-modal-label">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Delete User</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label asp-for="Username"></label>
                        <div asp-for="Username">@Model.Username</div>
                        <input hidden asp-for="Username" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </div>
        </div>
    </div>
</form>